kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    jarFileName: vpp-calculations.jar
    openshift.io/generated-by: OpenShiftWebConsole
  name: vpp-calculations
  namespace: vpp-central-services
  labels:
    app: vpp-calculations
    app.kubernetes.io/component: vpp-calculations
    app.kubernetes.io/instance: vpp-calculations
    app.kubernetes.io/name: vpp-calculations
    app.kubernetes.io/part-of: vpp-central-system-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-8-el7
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "vpp-calculations:latest"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "java:openjdk-8-el7"
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: vpp-calculations-generic-webhook-secret
  runPolicy: Serial